### ISSUE TITLE
Investigate whether pagination reduces offer request latency

### ISSUE THREAD

**Issue by bsotiroff** [cupofsugarCo/flying_penguin#45]
Since Duffel is a proxy, it can be prone to [long response times](https://duffel.com/docs/api/overview/response-times).

Currently the httpoison response timeout in the duffel client is set at an absurdly high 20s. I suspect that pagination may provide a better user experience with lower response times.

Testing from ORD to BKK typically seems to create a higher response time.
https://duffel.com/docs/api/overview/pagination

**Comment by olgashi** [comment]
@bsotiroff I looked at the documentation and it doesn't look like we can limit number of offers we receive when we create an offer request (they have that for 'list offers', but not for 'create offer request').

We probably just gonna have to deal with it, later we can add a spinner or loader of some sort to indicate to the user that the page is  in the process of loading the results.

**Comment by bsotiroff** [comment]
thanks for looking into this. I think there are some gains that can be made by splitting up the requests for departure and return flights like we talked about last week.
