### ISSUE TITLE
Remove unused files from the project

### ISSUE THREAD

**Issue by olgashi** [cupofsugarCo/flying_penguin#64]
I suspect there are some unused files in the project (that came with the project boilerplate).

If that is the case, we should go through folders and remove files that are not being used

This would help to better learn the project structure and make the project easier to navigate.

To do:

- [ ]  Investigate if there are files in the project that can (and should be) removed
- [ ] Remove them

**Comment by bsotiroff** [comment]
lets go through the file structure Saturday. I think there is a lot of generated stuff related to phx.gen.auth. This establishes users and auth. There is also some minimal config for Bamboo, which is an elixir dependency that sends email. I had put this in the generator bc I originally had plans for that functionality even though we haven't necessarily gotten to it.
